# Generated on Fri Feb  8 19:30:57 2019
__collection-name__: simulator-parameters

dynamics_dt                      : 0.001
floor_kd                         : 5000
floor_kp                         : 500000
game_controller_deadband         : 0.01
high_level_dt                    : 0.001
low_level_dt                     : 0.0002
simulation_paused                : 0
simulation_speed                 : 1.
sim_lcm_ttl                      : 0
sim_state_lcm                    : 1
use_spring_damper                : 0
vectornav_imu_accelerometer_noise: 0.005
vectornav_imu_gyro_noise         : 0.005
vectornav_imu_quat_noise         : 0.003
go_home                          : 0
home_pos                         : [0,0,.5]
home_rpy                         : [0,0,0]
home_kp_lin                      : 2500
home_kd_lin                      : 300
home_kp_ang                      : 250
home_kd_ang                      : 60
